### ISSUE TITLE
Domain Name With Host Computer[FEATURE REQUEST]

### ISSUE THREAD

**Issue by DankBoi293** [Poly-Development/PolyCloud#20]
I was wondering if someone has a spare computer they can use as a server.(https://blog.resellerclub.com/how-to-host-a-domain-website-on-your-own/)
With this we can maybe have our own email domains(@polycloud.com) and have our own domain(polycloud.com or .net)

**Comment by Lethdev2019** [comment]
I (sadly) can, but i would REALLY LOVE TO. if only i had my own computer and job but i'm a student.
also, there is a requirement, node 10.x and at least 4GB RAM with an access rate of 300mb/s min for smooth-ish performance.
