### ISSUE TITLE
Moving Blob w/ Canvas & JavaScript[FEATURE REQUEST]

### ISSUE THREAD

**Issue by DankBoi293** [Poly-Development/PolyCloud#22]
@Lethdev2019 I would like to encorporate [this blob](https://repl.it/@CodingAndMemes/Blob) into the login and verify pages. Just gonna throw that out there

**Comment by Lethdev2019** [comment]
@DankBoi293 
Ok, got a preview at https://polycloud.herokuapp.com/login.
Please tell me what you think.

- [x] add blob
- [ ] get feedback

**Comment by DankBoi293** [comment]
looks good, but check out [the repl](https://repl.it/@Lethdev2019/Blob). I made some changes

**Comment by DankBoi293** [comment]
also, the [polycloud login](https://polycloud.herokuapp.com/login) has the `<title>` "repl.it". so I think you should change that

**Comment by Lethdev2019** [comment]
@DankBoi293 Changed. now try it. (new favicon too!)
