### ISSUE TITLE
Double forward slash

### ISSUE THREAD

**Issue by camjac251** [Poly-Development/PolyCloud#3]
This might be an issue with your install of PolyCloud but when I upload on the official site, I get a double forward slash before the permalink

To replicate this use the web uploader and the link it generates has two forward slashes.

**Comment by Lethdev2019** [comment]
i know, but rules are rules, if it works, DON'T CHANGE IT.

**Comment by camjac251** [comment]
I'm confused? This is what I'm referring to
![image](https://user-images.githubusercontent.com/6313132/81321050-b915f580-9057-11ea-8c27-37cf650e2c62.png)

The link it makes it has an extra / after the domain name. Is this possibly set in your config 
```
	domain: 'https://polycloud.herokuapp.com/',
```

if you changed it to maybe

```
	domain: 'https://polycloud.herokuapp.com',
```
since the forward slash likely is redundant as it probably adds one for the url anyway

**Comment by Lethdev2019** [comment]
yes it is.

**Comment by DankBoi293** [comment]
> 
> 
> i know, but rules are rules, if it works, DON'T CHANGE IT.
"if it ain't broke, don't fix it"

**Comment by camjac251** [comment]
It is a bit broken if two forward slashes are added with the fixing being a simple removal of the above extra forward slash \

**Comment by camjac251** [comment]
All you have to do really is remove the forward slash here... It is that simple
https://github.com/Poly-Development/PolyCloud/blob/master/config.js#L29

**Comment by camjac251** [comment]
It is an easy fix. Just removing the forward slash here
https://github.com/uhthomas/kipp/blob/a367086282307625a8acb3364bee23fc1d7685c5/server.go#L203

**Comment by camjac251** [comment]
https://github.com/Poly-Development/PolyCloud/blob/9ec959849a4fe7338e19527fc666f63332e8819d/config.js#L29

The fix is easy. Just removing the forward slash at the end of this url will solve the problem

**Comment by Lethdev2019** [comment]
I know, i fixed/changed it (i already knew), i _had_ it purposely configured like that.
