### ISSUE TITLE
Broken hyperlink on upload page

### ISSUE THREAD

**Issue by camjac251** [Poly-Development/PolyCloud#4]
When I am on the upload page https://polycloud.herokuapp.com/upload and click Dashboard at the bottom right, it goes to https://polycloud.herokuapp.com/auth but if you are logged in, that page doesn't redirect to the dashboard, it just shows a 404 error

**Comment by Lethdev2019** [comment]
oh, sorry.
i'll not fuss and get to it.

**Comment by Lethdev2019** [comment]
a mean i'll get to it without complaining!

**Comment by Lethdev2019** [comment]
done
