### ISSUE TITLE
[BUG] account button broken

### ISSUE THREAD

**Issue by Codemonkey51** [Poly-Development/PolyCloud#5]
**account button broken**
The account button doesn't work.

**To Reproduce**
1. Login/signup
2. Click account
3. See that it doesn't work

**Expected behavior**
Send me to the account page

**Comment by Lethdev2019** [comment]
can you give screenshots?

**Comment by Codemonkey51** [comment]
I can't my account is no longer working and it says an error occurred

**Comment by Codemonkey51** [comment]
Used new account can't get screen shot :/

**Comment by Lethdev2019** [comment]
it's because i'm updating it like a ######## rn

**Comment by Codemonkey51** [comment]
Um it \#'ed a word

**Comment by Lethdev2019** [comment]
it's swearing, so please don't ask.

**Comment by Lethdev2019** [comment]
fixed now?

**Comment by Lethdev2019** [comment]
it does work, for you a legacy browser

**Comment by DankBoi293** [comment]
> I can't my account is no longer working and it says an error occurred
@Codemonkey51 
Yeah, it seems that it does that for me too.

**Comment by Lethdev2019** [comment]
oh, when heroku updates the webpage, your browser will still have the auth cookie loaded, this causes the page to send a login request for user which no longer exists due to the data base being wiped on updates.

**Comment by Lethdev2019** [comment]
i don't know how to get heroku to save the database.

**Comment by Lethdev2019** [comment]
or the files

**Comment by Lethdev2019** [comment]
we still are updating it...

**Comment by DankBoi293** [comment]
We will reopen this issue after the update
