### ISSUE TITLE
Error 404 at contact hyperlink

### ISSUE THREAD

**Issue by bobNeo** [Poly-Development/PolyCloud#7]
**Describe the bug**
Error 404 error when you press contact, not sure if this is just unfinished or if that’s a bug.

**To Reproduce**
1. Go to home
2. Click on contact

**Expected behavior**
Either a page saying it’s unfinished or something.

**Comment by DankBoi293** [comment]
Hi @bobNeo , I have made a proposed webpage for this issue [here](https://github.com/Poly-Development/PolyCloud/compare/master...DankBoi293:patch-2). Thanks!

btw, if you could reply with your contact info so I can add it that would be great.

**Comment by Lethdev2019** [comment]
configurated...

**Comment by Lethdev2019** [comment]
also i'll have a discord open soon.

**Comment by Lethdev2019** [comment]
ok fixed contacts is open!
